# Generated by Django 4.2.4 on 2024-08-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('entertainment', 'Entertainment'), ('utilities', 'Utilities'), ('shopping', 'Shopping'), ('health', 'Health'), ('education', 'Education'), ('others', 'Others')], max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit Card'), ('bank', 'Bank'), ('transfer', 'Transfer'), ('others', 'Others')], max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
