# Generated by Django 4.2.4 on 2024-08-28 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recurring_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurring',
            name='expense',
        ),
    ]
