# Generated by Django 4.2.4 on 2024-08-28 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0002_initial'),
        ('recurring_app', '0002_remove_recurring_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_patterns', to='expense_app.expense'),
        ),
    ]
