# Generated by Django 4.2.4 on 2024-08-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurring_app', '0003_recurring_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring',
            name='end_date',
            field=models.DateField(),
        ),
    ]
