# Generated by Django 4.2.4 on 2024-08-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurring_app', '0004_alter_recurring_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
