# Generated by Django 4.2.4 on 2024-08-28 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recurring_app', '0005_alter_recurring_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_patterns', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
