# Generated by Django 4.2.4 on 2024-08-28 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('income_app', '0001_initial'),
        ('budget_app', '0001_initial'),
        ('recurring_app', '0006_recurring_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='income',
            field=models.ManyToManyField(blank=True, related_name='budget', to='income_app.income'),
        ),
        migrations.AddField(
            model_name='budget',
            name='recurring',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='recurring_app.recurring'),
        ),
        migrations.AddField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to=settings.AUTH_USER_MODEL),
        ),
    ]
