# Generated by Django 4.2.4 on 2024-08-28 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recurring_app', '0006_recurring_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('source', models.CharField(choices=[('salary', 'Salary'), ('freelancing', 'Freelancing'), ('investment', 'Investment'), ('business', 'Business'), ('gifts', 'Gifts'), ('others', 'Other')], max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField(max_length=255)),
                ('category', models.CharField(choices=[('primary', 'Primary Income'), ('secondary', 'Secondary Income'), ('passive', 'Passive Income'), ('supplementary', 'Supplementary Income'), ('others', 'Other Income')], max_length=255)),
                ('recurring', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income', to='recurring_app.recurring')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
